build:
  verbosity: minimal

branches:
  only:
    - master  
  
image: Visual Studio 2015

platform: x64

configuration: Release

test: off

environment:
    REPO_DIR: &REPO_DIR c:\tsunami
    SQUIRREL_DIR: &SQUIRREL_DIR c:\squirrel
    SQUIRREL_URL: https://github.com/Squirrel/Squirrel.Windows/releases/download/1.7.8/Squirrel.Windows-1.7.8.zip

# project directory
clone_folder: *REPO_DIR

install:
  - set QTDIR=C:\Qt\5.8\msvc2015_64
  - set PATH=%PATH%;%QTDIR%\bin

before_build:
  - ps: $V_MAJ=select-string -Path ".\version.pri" -Pattern "VER_MAJOR ="
  - ps: $V_MAJ="$V_MAJ"
  - ps: $V_MAJ=$V_MAJ.split()[-1]
  - ps: $V_MIN=select-string -Path ".\version.pri" -Pattern "VER_MINOR ="
  - ps: $V_MIN="$V_MIN"
  - ps: $V_MIN=$V_MIN.split()[-1]
  - ps: $V_BUG=select-string -Path ".\version.pri" -Pattern "VER_BUGFIX ="
  - ps: $V_BUG="$V_BUG"
  - ps: $V_BUG=$V_BUG.split()[-1]
  - ps: Update-AppveyorBuild -Version "$V_MAJ.$V_MIN.$V_BUG"
  
build_script:
  - appveyor DownloadFile "%TSU_LIB_URL%" -FileName "c:\libraries.7z" && 7z x "c:\libraries.7z" -o"%REPO_DIR%"
  - '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64'
  - qmake Tsunami.pro
  - nmake release
  #- cp lib_rel/*.dll release
  - xcopy lib_rel release /E /Y
  - cp CHANGELOG.md  release
  - cd release
  - del /Q *.cpp
  - windeployqt --release --no-opengl-sw --no-translations Tsunami.exe
  - del /Q libGLESV2.dll libEGL.dll d3dcompiler_47.dll
  - appveyor DownloadFile "%SQUIRREL_URL%" -FileName "C:\squirrel.zip" && 7z x "C:\squirrel.zip" -o"%SQUIRREL_DIR%"
  - ps: nuget pack c:\tsunami\Tsunami.nuspec -Version "$V_MAJ.$V_MIN.$V_BUG" -Properties Configuration=Release -BasePath .
  - cd "%SQUIRREL_DIR%"
  - ps: .\Squirrel.com -r c:\tsunami\Releases --icon=c:\tsunami\images\logo_tsunami_big.ico --setupIcon=c:\tsunami\images\installer_icon.ico --no-msi --releasify c:\tsunami\release\Tsunami."$V_MAJ.$V_MIN.$V_BUG".nupkg 
  #- ps: rm c:\tsunami\Releases\Setup.exe 
  
cache: 
  - Releases/

artifacts:
  - path: Releases/0.5.*.nupkg
    name: TsuNugets

  - path: Releases/Setup.exe 
    name: TsuSetup
    
  - path: Releases/RELEASES
    name: TsuRelFile
    
deploy:
  - provider: Environment
    name: GH
  - provider: Environment
    name: AdunanzA
