build:
  verbosity: minimal
  
  
image: Visual Studio 2015

platform: x64

configuration: Release

environment:
    REPO_DIR: &REPO_DIR c:\tsunami
    SQUIRREL_DIR: &SQUIRREL_DIR c:\squirrel
    TSU_LIB_URL: https://tsunami.adunanza.net/devs/libraries.7z
    SQUIRREL_URL: https://github.com/Squirrel/Squirrel.Windows/releases/download/1.7.8/Squirrel.Windows-1.7.8.zip
    priv_key:
    secure: 3h4c8Dn5tO+SPC0zI8sd3KgDopyNfND5A133ygpVdeLPfsDWvFjAfky/uNH3O8lKZoX/KywB7BhRvC+VGp3+ia7NLc/v275HjEYg4AClZ3WLlR/Awt5ogQEq+VIm20VPuwoOf8X4E+dzjs2rFgt+6onVnrpsmPR/iJIk/dDEfNCisaS/tTKtEY/v14ylCUSpX0sgQgxBKPyeBlrlSQZBo/spcGemgDBnexGhqWA/MLTgdDGOmXf8V/CenQQgMmLxxqS51YGzy9O7xpzCmQba9TCbFBk/g/8wJxlNKSXqVUv02yFjDTp1Zozm4zNVHv7pHe99jRwfqn/hDKT+W02yRvgLfe7OKpLPE1m1aD911KlylgQ261wNb5/H2srMlkNcTyI1GgptPLdBKyciLrtLTZ3blQrljowFY23ncOc8IHyn7o67D7Sb2r1AtLhBhOLTgRFpUegFWLgD/lPzpU2XcB8FvhRYoef2sg0B5WJJFozJ+khfEZX3qa8lP4gA6ME8LNXfhXziba+en/Q5+UNPdLkB5WZA6MSbUlNffcuDCnwPghkshOOrArge+NO5Hf0+mdr3ZM19tS52X48VETMfk11fccyDoZt1KdGHGwG22bhh6AKswUt1ZBRW0l7vuEUgJCtbFlJjeAFkOV515Xr9/KfkkUJrFT7wW2tjLvI0uT+bV3HQ94ovFS8Ij4m3vSdORI+TZn5myXMQdXmH07jQxXTkCYRK5eUluNlJF21ALhdvWfdaJUHA1N+SrLLxBoyMs2ha6WeVSmWiOhBJS6RCwFoHvIMtF75j8Pz+LZV12w4TITw7gvUH09HV5TBU/HkVjQSUr6JTujzwBGcIWUqA0II4lZaysLNP+9ymWGDXBqrnqLBQgo4LGroRgamhg1A3Pl7k7TuaMqQZeTQ5lfU3YSVOyKerpvDVFA6PoohpN6hImVEQOM+SclUQNSwvYvj+/YiRvWv8fm50YJ9V2Sdiy5mkri+EJwTpuyJ/vPvZycoAHEvxbv994rYkt+t4B7LzVojkgWcRw2V+B55HUDnQlQ8J68q03KBDRvh8GDDZHNNN3i+5zdlXg27ixPmiVmktDEmQYPRoWshRD0H52OnI6lcDSIfgvvUArMr2vvFu7W7+jR0rZhmQ4WpUQ8l42/3O/RhDRzYEjAsWvLunr+fF33UqF3yJ5wa375vOcKs/IrNIEk8+hqXOzLTsOGZw4P7bcHrbX7QCm8/lYIxCwVnLuyDulDt6sprii2Qw+Qr0P5PfyVkM2LKOq+FNfdiuOS8r5uFXg9hKk4w4s+Gm84vKQrHGylTsDiLs02tFoNEnoWRtqMg4uCWThkjFB/OQKxQe0gH4F1wxQoQzbELwD1VJdttM1m7kmKpA2uqVcCDCWwARuOQT0KgRltzwI6tP+H7I1pq+Ln+Ew6ICNU8hFF8JFBQQSIuLzwHKkp6cVzFtBHQZQ57Q8x+6ftxmHqeaNJBzMglsEejmcvCBZa2/wYT9pjxufAymJ7cc1X6CR2DeIx2lzrmt32G2icWqkr0SALnQ5aFQO+h9+OI4rsEZCVKLobWtZJvmIS0QSEzeThiKKZ1hLQLtZrRLPPWvI/9nHdl6epHR1nkMeGioAvsxdc54n2vukllo9aVJ4xZtsb9Z7123+bvi7swmQF95irdZfA/FVDUliefRMod+E8086cq11520tY+zm6gPwNWf5Jln5dl6xb3qqWd//uJBoqpRcKiNbG8HtbSFEm+7sohd3yP2qk5InXWfpuG0XxTvuTZMv6U1FHB9t/POMTuHAUP/o1AWZ08pxQR8vM3ePDb4EetC7GqTYWtiwQb3u9diDKRKx77vapIk6Jy5QG69zcKDGDGSyCksk1u/4pNg1cuDdkBSPIrDIbwwnU1eRpyZNdi+wYqaS8sNhZYU8t/rLU27PiwKAkf58y/FTKF4By4lSYORici7PkyydUB5rXBJ9avoarEwMD1EaVZLaaFGsm+ks7nmsdLEhnfy+H3zakotC/FyFrQjSM4Do3nDB0gKsj0wl45VKXULgApmeukqAsHdeGV/sQc/0BpJdpFrJzhvOx2wwMDGRF4sDrBPIeq5Wkwr7fS/7R9JBurVvx/7WFR61Mazdz8OWEuLWVtMKE+6ngnt0SF7SqhMFRQnDGxEYGeNJ2QBH7kpmd62No1Lk7elOdRF

# project directory
clone_folder: *REPO_DIR

install:
  - set QTDIR=C:\Qt\5.8\msvc2015_64
  - set PATH=%PATH%;%QTDIR%\bin
  - ps: $fileContent = "-----BEGIN RSA PRIVATE KEY-----`n"
  - ps: $fileContent += $env:priv_key.Replace(' ', "`n")
  - ps: $fileContent += "`n-----END RSA PRIVATE KEY-----`n"
  - ps: Set-Content c:\users\appveyor\.ssh\id_rsa $fileContent
  #- git submodule update --init --recursive

before_build:
  - ps: $V_MAJ=select-string -Path ".\version.pri" -Pattern "VER_MAJOR ="
  - ps: $V_MAJ="$V_MAJ"
  - ps: $V_MAJ=$V_MAJ.split()[-1]
  - ps: $V_MIN=select-string -Path ".\version.pri" -Pattern "VER_MINOR ="
  - ps: $V_MIN="$V_MIN"
  - ps: $V_MIN=$V_MIN.split()[-1]
  - ps: $V_BUG=select-string -Path ".\version.pri" -Pattern "VER_BUGFIX ="
  - ps: $V_BUG="$V_BUG"
  - ps: $V_BUG=$V_BUG.split()[-1]
  - ps: Update-AppveyorBuild -Version "0.$V_MIN.$V_BUG.$env:appveyor_build_number"
  
build_script:
  - appveyor DownloadFile "%TSU_LIB_URL%" -FileName "c:\libraries.7z" && 7z x "c:\libraries.7z" -o"%REPO_DIR%"
  - '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64'
  - qmake Tsunami.pro
  - nmake release
  - cp lib_rel/*.* release
  - cd release
  - windeployqt --release Tsunami.exe
  - appveyor DownloadFile "%SQUIRREL_URL%" -FIleName "C:\squirrel.zip" && 7z x "C:\squirrel.zip" -o"%SQUIRREL_DIR%"
  - ps: nuget pack c:\tsunami\Tsunami.nuspec -Version "0.$V_MIN.$V_BUG" -Properties Configuration=Release -BasePath .
  - cd "%SQUIRREL_DIR%"
  - ps: .\Squirrel.com -r c:\tsunami\Releases --no-msi --releasify c:\tsunami\release\Tsunami."0.$V_MIN.$V_BUG".nupkg 
  
artifacts:
  - path: Releases
    name: Tsunami
    on:
      branch: master
      platform: x64
 #  **\*.nupkg
