name: tsunami
version: "0.6.2"
summary: AdunanzA Tsunami
description: a very cool torrent client written in Qt and Libtorrent :)
confinement: strict
grade: devel

apps:
  tsunami:
    command: desktop-launch $SNAP/usr/bin/Tsunami
    plugs: [unity7, x11, opengl, network, home, pulseaudio]

parts:
  application:
    source: .
    plugin: qmake
    qt-version: qt5
    build-packages:
      - libboost-system-dev
      - libvlc-qt-dev
      - libtorrent-rasterbar-dev
      - libssl-dev
      - libglu1-mesa-dev
      - qtdeclarative5-dev
      - qtscript5-dev
      - qtbase5-dev
      - g++
    stage-packages:
      - libtorrent-rasterbar9
      - libvlc-qt-core2
      - libqt5script5
      - libvlc-qt-widgets2
      - libqt5gui5
      - qmlscene
      - libglu1-mesa
      - libgpm2
      - zlib1g
      #- libcanberra-gtk3-module
    override-build: |
      # needed in order compile with libtorrent-rasterbar-dev
      #sed -i -e 's|/usr/bin|$SNAPCRAFT_PART_INSTALL|g' Tsunami.pro
      sed -i -e 's/DEFINES += TORRENT_NO_DEPRECATE/#DEFINES += TORRENT_NO_DEPRECATE/g' Tsunami.pro
      qmake Tsunami.pro
      make clean
      snapcraftctl build
      make install 
    after: [desktop-qt5] #, qtcharts]

  desktop-qt5:
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - locales-all

#  qtcharts:
#    plugin: qmake
#    source: https://github.com/qt/qtcharts.git
#    source-tag: release-2.1.0
#    qt-version: qt5
#    build-packages:
#      - qt5-default
#      - qtbase5-dev
#      - qttools5-dev
#      - build-essential
#      - qttools5-dev-tools
